fixes #101
env0/terratag pull request #102
Opened 2021-11-08 13:06 UTC by ezraroi

2021-11-09 12:50 UTC, yaronya commented
Hi @ezraroi 
Thanks for your contribution! 🙏 

Please make sure:
1. PR has a valid title and description (we should be adding PR guidelines soon, sorry bout that tho)
2. CI tests pass

2021-11-10 14:12 UTC, ezraroi commented
fixes #101

2021-11-10 14:12 UTC, ezraroi commented
@yaronya looks like it took it 2 days to run the tests

2021-11-11 13:29 UTC, ezraroi commented
Also removed the `bucket_policy_only` from tests as it deprecated

2021-11-16 09:11 UTC, yaronya commented
> @yaronya looks like it took it 2 days to run the tests

@ezraroi yup we required approval for runs of forked repositories of first-time contributors 🙏 
Sorry for the delay - I've now approved your recent changes and it tests seem to pass

2021-11-16 11:45 UTC, eranelbaz requested changes
Hey!
from first impression looks like `ConcatTagsToTagsBlock` is copy-paste from `TagBlock`,
and its also hard to read and reason with this pr without any description that explain what you did.

I think what we actually want to do here is make `TagBlock` support your issue

2021-11-21 06:56 UTC, ezraroi commented on tagging/tagging.go
> +func ConcatTagsToTagsBlock(args TagBlockArgs) string {
No to Tag, but to tags. If the user used the Tags block we need to append the tags to the Tags block. Otherwise, we can just add more tag blocks

2021-11-21 06:57 UTC, ezraroi commented
> 

The issue that is linked to the PR is explaining the problem we face

2021-11-21 07:05 UTC, ezraroi commented
> 

Also it is not copy-paste, it is not doing the same thing.
I dont need to call `convert.MoveExistingTags` in my code and also there is no need to search if there is a block as this is a concat function that adds tags to existing block.

I will try to extract some common code from both of them

2021-11-21 09:35 UTC, eranelbaz commented on tagging/tagging.go
> +func ConcatTagsToTagsBlock(args TagBlockArgs) string {
So `TagToTags` since you set `TagsToTags` its hard to understand what you append where

2021-11-21 09:35 UTC, eranelbaz commented
> The issue that is linked to the PR is explaining the problem we face

The issue explain the problem, the PR description explain the solution for the issue

> I will try to extract some common code from both of them

Thanks 🙏

2021-11-21 13:16 UTC, eranelbaz requested changes
> I dont need to call `convert.MoveExistingTags` in my code and also there is no need to search if there is a block as this is a > concat function that adds tags to existing block.

Looks like you are calling that here 

https://github.com/ezraroi/terratag/blob/d4a263840842d66218d40866802ceb1640704e76/tagging/tagging.go#L47-L50

The current architecture of this code should be in a different way - 
for each specific logic of a resource we run the relevant logic inside the cloud-provider file, in this case - `tagging/aws.go`
then we can change the way this resource is written by covert the `tags` block to multiple `tag` blocks then the rest of our code can run at the same way

you can take a look at the current comment we have 
https://github.com/env0/terratag/blob/740166c4aba6b792fe43635c0464f99cd96a49a0/tagging/aws.go#L8-L10

can we do that?

Thanks

2021-11-22 08:35 UTC, ezraroi commented
> https://github.com/ezraroi/terratag/blob/d4a263840842d66218d40866802ceb1640704e76/tagging/tagging.go#L47-L50

Sorry, yes i am calling it.
I extracted some of the common code to share methods anyway.

So you suggest to change the `tags` block to multiple `tag` blocks? Why? this will change the code the user provided in his terraform file. I think the current implementation does not break what you wrote.

The comment you mentioned is the problem that i am trying to fix. The idea is to support both use cases.

2021-11-22 15:16 UTC, eranelbaz commented
> > [ezraroi/terratag@`d4a2638`/tagging/tagging.go#L47-L50](https://github.com/ezraroi/terratag/blob/d4a263840842d66218d40866802ceb1640704e76/tagging/tagging.go#L47-L50)
> 
> Sorry, yes i am calling it. I extracted some of the common code to share methods anyway.
> 
> So you suggest to change the `tags` block to multiple `tag` blocks? Why? this will change the code the user provided in his terraform file. I think the current implementation does not break what you wrote.
> 
> The comment you mentioned is the problem that i am trying to fix. The idea is to support both use cases.

So the way terratag works today is by changing the `tf` code of the client in order to add those `tag`/`tags` attributes for the relevant resources

I don't find any reasons why we shouldn't do the same here

2021-12-12 18:14 UTC, avnerenv0 commented
Hey @ezraroi 

Please respond to @eranelbaz 's requests.
If this PR won't be touched in 3 days I will close it for being stale.

Thank the contribution.

2021-12-15 14:03 UTC, avnerenv0 commented
Closing stale

2021-12-15 14:03 UTC, closed without merging

2021-12-17 08:17 UTC, jeffliu527 commented
met with the same issue while creating an AWS bastion server using: https://github.com/Guimove/terraform-aws-bastion , if @ezraroj 's solution cant be accepted, pls advise how to fix this issue.

Error message:

│ Error: Conflicting configuration arguments
│
│ with module.bastion.module.bastion.aws_autoscaling_group.bastion_auto_scaling_group,
│ on .terraform/modules/bastion.bastion/main.terratag.tf line 330, in resource "aws_autoscaling_group" "bastion_auto_scaling_group":
│ 330: tags = concat(
│ 331: tolist([tomap({
│ 332: "key" = "Name"
│ 333: "value" = "ASG-${local.name_prefix}"
│ 334: "propagate_at_launch" = true
│ 335: })]),
│ 336: local.tags_asg_format
│ 337: )
│
│ "tags": conflicts with tag